SELECT CITY, LENGTH(CITY)
FROM STATION
WHERE CITY = (
    -- QUERY RETURN MAX LENGTH CITY NAME
    SELECT CITY
    FROM (
        SELECT CITY, LENGTH(CITY)
        FROM STATION
        ORDER BY LENGTH(CITY) DESC, CITY
    )
    WHERE ROWNUM = 1
)
OR CITY = (
    -- QUERY RETURN MIN LENGTH CITY NAME
    SELECT CITY
    FROM (
        SELECT CITY, LENGTH(CITY)
        FROM STATION
        ORDER BY LENGTH(CITY), CITY
    )
    WHERE ROWNUM = 1
);